### ISSUE TITLE
GHC 8.4.x compability

### ISSUE THREAD

**Issue by emanuelbuholzer** [adnelson/semver-range#10]
Support for the new version of GHC would be cool. With GHC 8.4.x Semigroup becomes a superclass of Monoid. The following doesn't seem to work when building with a newer version of GHC:
```Haskell
-- src/Data/SemVer/Types
newtype PrereleaseTags = PrereleaseTags [PrereleaseTag]
  deriving (Show, Eq, Monoid, Generic)
```
Thus generates the following error message:
```
src/Data/SemVer/Types.hs:37:23: error:
    • No instance for (Semigroup PrereleaseTags)
        arising from the 'deriving' clause of a data type declaration
```
One way to fix this problem (probably not backward) is to derive from Semigroup too. Other than that there is the following upgrade guide: https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid#Writingcompatiblecode

Let me know what you prefer, I'm happy to open a PR.

**Comment by gbaz** [comment]
Bump.

**Comment by adnelson** [comment]
I really dropped the ball here, apologies... but I think this is fixed now!
